### ISSUE TITLE
Error message on unresolved files is terrible!

### ISSUE THREAD

**Issue by aredridel** [krakenjs/engine-munger#22]
We don't give an error about what file we looked for and where we looked for it, just a couple undefined in an object, which we then try to pass to rendering, which fails because undefined isn't a valid template name.

**Comment by briemens** [comment]
Indeed! Here is a PR which throws an error when a resource is not found. https://github.com/krakenjs/engine-munger/pull/23

**Comment by aredridel** [comment]
Fixed in #30, but reworks the API.
