### ISSUE TITLE
Getting a localized string when not in a template

### ISSUE THREAD

**Issue by AleCaste** [krakenjs/engine-munger#28]
The library works very well working within dust templates.
But there are times when the application needs access to localized strings and we are not rendering a template (e.g. let's imagine we are responding to an ajax request with JSON data and part of that data are localized strings to be displayed to the user... there is no template being rendered and still we need to get some localized strings)...
Is it possible to address this issue somehow?

**Comment by aredridel** [comment]
Yes! check out the [bundalo](https://github.com/krakenjs/bundalo/) package!

**Comment by AleCaste** [comment]
Hahahaha wow! Another package??? This puzzle has so many pieces!
But that's ok. At least all the angles are covered! Well done; we'll have a look at bundalo

**Comment by aredridel** [comment]
Yep! I'm hoping to write some overarching docs this week. Maybe that'll help some!

**Comment by aredridel** [comment]
(In theory, smaller packages should churn less, and it's at least nice to have a name to refer to them by.)
