### ISSUE TITLE
Application becomes unresponsive when a load test is done after server startup

### ISSUE THREAD

**Issue by brakon** [krakenjs/engine-munger#37]
When we restart the kraken application and send a load test against it, the instances become unresponsive.

By adding logging I noticed that the unresponsive instances when on the limitStat function, they are over the threshold of 10, in which the event is queued in pendingStats.push, but it never gets dequeued.

On a **unresponsive** instance with logging I see:

```
(out): adaro engine method
(out): after aproba in engine
(out): before adaro dust get context
(out): call to dust.render in adaro
(out): dust on load
(out): dust on load
(out): dust on load
(out): on limit stat method
(out): limit over 10: 259
(out): on limit stat method
(out): limit over 10: 260
```

In an responsive instance I see:

```
bc-frontend-8001-1 (out): adaro engine method
bc-frontend-8001-1 (out): after aproba in engine
bc-frontend-8001-1 (out): before adaro dust get context
bc-frontend-8001-1 (out): call to dust.render in adaro
bc-frontend-8001-1 (out): dust on load
```

If I do a less intensive load test it works correctly, and if I do a more intensive load test after the less intensive load test it also works, seems this only happens when I restart the application and run an intensive load test without _warm up_

**Comment by aredridel** [comment]
Indeed: content will tend to be cached. Does the instance actually go unresponsive, or do the calls actually clear if you don't overload it? (is it a permanent condition?)

**Comment by brakon** [comment]
after the load test finishes, the instances are unresponsive, if you just do a single request it just hangs, you need to restart the server to be able to have the application respond again.

The code in question is:

```
function limitStat(path, cb) {
    debug('stat "%s"', path);
    if (++numPendingStats > 10) {
        pendingStats.push([path, cb]);
    } else {
        fs.stat(path, dequeue(cb));
    }
```

Basically it seems ones its queued, there is nothing dequeuing it.

I can continue doing single requests, and all them will just hang, and the logs will say that the numPendingStat increases on every request.

**Comment by aredridel** [comment]
Hmm. Returning stats should dequeue. Looks like time for me to make a test case!

**Comment by brakon** [comment]
What seems confusing also is:

```
function dequeue(cb) {
        return function (err, stat) {
            cb(err, stat);
            var next = pendingStats.shift();
            if (next) {
                fs.stat(next[0], dequeue(next[1]));
            } else {
                numPendingStats--;
            }
        };
    }
```

Since its reducing the numPendingStats by 1, only when there is no other pending stat available, but it should be doing the subtraction on each dequeue event.

**Comment by aredridel** [comment]
You seem to be right! If you move the `numPendingStats--` above   the if, does that fix it for you?

**Comment by brakon** [comment]
yes it does :)

How soon could this be fixed? if not soon, how would I go around it? since basically if we are under heavy load after an instance restart the application will be unresponsive

**Comment by aredridel** [comment]
Should be fixed by https://github.com/krakenjs/engine-munger/pull/38

**Comment by aredridel** [comment]
Landing that ASAP

**Comment by brakon** [comment]
Fix worked thanks, BTW why are you setting a limit of 10 and didn't make it configurable (and why limit it at all)

**Comment by aredridel** [comment]
Well, in plain express, it's actually synchronous, and so limit = 1. I don't want it eating all the file descriptors if someone gets hammered and make it impossible for _their_ code to execute without something like graceful-fs and its possibility of lockups if you don't coordinate well. 10 is a very reasonable concurrency on modern file systems and computers. Much more pending IO than that gets you no speedup, so you might as well queue in userland rather than kernel space where it eats a file descriptor.
