### ISSUE TITLE
Rendering correct paths in HTML output

### ISSUE THREAD

**Issue by Ampakinetic** [krakenjs/engine-munger#40]
I'm using iisnode and trying to render content from within a sub-folder of our main app.  The node app is hosted at /node/dust but the html coming out is referring to resources off the root path.  

I've tried setting the kraken basedir but the file output from the Kraken with Specialization example for the main style sheet is "/css/app.css" 

How could I make it say "/node/dust/css/app.css" ?

**Comment by aredridel** [comment]
Update the templates with the correct path -- and if that can vary, parameterize it, and pass the root URL in in the context.

**Comment by Ampakinetic** [comment]
I've tried that, but eg the app.css doesn't exist because it's a .less file - I thought there must be some server side compilation process that intercepts the request and hands out a .css file, and that it may need extra configuration.  I am probably missing something basic sorry.

**Comment by aredridel** [comment]
Indeed! In dev mode, people use `kraken-devtools`, which is in the `config/development.json` file; that's rapidly being replaced with `construx`, which is a cleaned-up devtools with a more fun name. In production, people prebuild, so run `grunt build`, which will build things into `.build`, and the static server can serve from there.

**Comment by Ampakinetic** [comment]
Ok, thank you so much!  I have run the grunt build command and it's created the .css files in the .build folder.  The dust template still has `<link rel="stylesheet" href="css/app.css" />` in it at the moment, the full page output is now: 

```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><title>Kraken with Specialization</title><link rel="stylesheet" href="css/app.css" /></head><body><div id="wrapper"><link rel="stylesheet" href="css/app.css" /><h1></h1><p>In Chinese philosophy, the concept of yin-yang (simplified Chinese: 阴阳; traditional Chinese: 陰陽; pinyin: yīnyáng), which is often called "yin and yang",is used to describe how opposite or contrary forces are interconnected and interdependent in the natural world; and, how they give rise to each other as they interrelate to one another.</p><div class="center transbox"><div><table><tr><td><img src="img/yinyang.gif"></td></tr><tr><td>Today is a balanced yin-yang day !</td></tr><tr><td>Four Main Aspects of Yin and Yang Relationship:<ul><li>Yin & Yang are opposites </li><li>Yin & Yang are Interdependent</li><li>Relative levels of Yin Yang are continuously changing. </li><li>Inter-transformation of Yin & Yang</li></ul></td></tr></table></div></div></div><script data-main="/js/app" src="js/lib/require-2.1.6.js"></script></body></html>
```

The CSS and JS isn't loading with those relative paths, nor on /node/dust/css/app.css , or /node/dust/.build/css/app.css.  

My config file essentially the default:

```
{
    "express": {
        "view cache": false,
        "view engine": "dust",
        "views": "path:./public/templates"
    },

    "view engines": {
        "dust": {
            "module": "makara",
            "contentPath 
            "renderer": {
                "method": "dust",
                "arguments": [
                    { "cache": true }
                ]
            }
        }
    },

    "specialization": "import:./specialization.json",

    "i18n": {
        "contentPath": "path:./locales",
        "fallback": "en-US"
    },


    "middleware": {

        "static": {
            "module": {
                "arguments": [ "path:./.build" ]
            }
        },

        "router": {
            "module": {
                "arguments": [{ "index": "path:./routes" }]
            }
        },

        "makara": {
            "priority": 100,
            "enabled": true,
            "module": {
                "name": "makara",
                "arguments": [ {
                    "i18n": "config:i18n",
                    "specialization": "config:specialization"
                } ]

            }
        },

        "fileNotFound": {
            "enabled": true,
            "priority": 130,
            "module": {
                "name": "kraken-js/middleware/404",
                "arguments": [ "errors/404" ]
            }
        },

        "serverError": {
            "enabled": true,
            "priority": 140,
            "module": {
                "name": "kraken-js/middleware/500",
                "arguments": [ "errors/500" ]
            }
        },

        "spclContext": {
            "enabled": true,
            "priority": 105,
            "module": {
                "name": "path:./lib/specialization"
            }
        }

    }

}
```

I'm still missing something I guess?

**Comment by aredridel** [comment]
Yeah, there's no magic going on here: The browser interprets the html from that template the normal way, and resolves paths relative to the URL loaded. You'll have to adjust the template, likely, if you're in a non-root folder.

**Comment by Ampakinetic** [comment]
Ok cool, all good now, it was the order of my IIS modules config, the node hander was getting in the way of the static files.  I really appreciate your time helping me to get this going.

**Comment by aredridel** [comment]
Glad to help! Yay!
