### ISSUE TITLE
Engine-Munger always uses fallback locale for included template lookup

### ISSUE THREAD

**Issue by nerdgore** [krakenjs/engine-munger#41]
It seems that the latest npm version 1.1.1 does not lookup included files correctly.
According to the debug output below only the main template is correctly found with the localised version. All included partials are only searched for the fallback language. This does not affect properties files.

The app is setup as in the read me example:

``` javascript
const I18N_CONFIG = {
        contentPath: "locales",
        fallback: "de-DE",
        formatPath
    };

if (app.get("env") === "development") {
    app.engine("dust", adaro.dust(DUST_CONFIG));
    app.set("views", path.join(config.root, "app/views"));
    app.set("view engine", "dust");
} else {
    app.engine("js", adaro.js(DUST_CONFIG));
    app.set("views", path.join(config.root, "build/app/views"));
    app.set("view engine", "js");
}

app.set("view", munger({
    "properties": {
        root: [I18N_CONFIG.contentPath],
        i18n: I18N_CONFIG
    },
    "js": {
        root: "build/app/views",
        i18n: I18N_CONFIG
    }
}));
```

The template to render is composed of an included layout and some partial includes.

```
{>"layouts/master" /}
{<body}
    {>"header" /}
   {!...snip...!}
{/body
```

From the debug output:

```
ENGINE-MUNGER 92843: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 92843: lookup "home.js"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/build/app/views/RU/ru/home.js"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/build/app/views/RU/ru/home.js"
ENGINE-MUNGER 92843: render "~/workspace/node-app/dist/public-home-germany-node/build/app/views/RU/ru/home.js"
ADARO 92843: loading '~/workspace/node-app/dist/public-home-germany-node/build/app/views/RU/ru/home.js' directly as it is an absolute path
ADARO 92843: loaded '~/workspace/node-app/dist/public-home-germany-node/build/app/views/RU/ru/home.js' as 'home'
ENGINE-MUNGER 92843: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 92843: lookup "home.properties"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/home.properties"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/home.properties"
ENGINE-MUNGER 92843: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 92843: lookup "home.properties"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/home.properties"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/home.properties"
ADARO 92843: looking up 'layouts/master' using view engine
ENGINE-MUNGER 92843: trying locales ["DE/de"]
ENGINE-MUNGER 92843: lookup "layouts/master.js"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/build/app/views/DE/de/layouts/master.js"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/build/app/views/DE/de/layouts/master.js"
ADARO 92843: loaded '~/workspace/node-app/dist/public-home-germany-node/build/app/views/DE/de/layouts/master.js' as 'layouts/master'
ENGINE-MUNGER 92843: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 92843: lookup "layouts/master.properties"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/layouts/master.properties"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/layouts/master.properties"
ENGINE-MUNGER 92843: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 92843: lookup "layouts/master.properties"
ENGINE-MUNGER 92843: stat "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/layouts/master.properties"
ENGINE-MUNGER 92843: found "~/workspace/node-app/dist/public-home-germany-node/locales/RU/ru/layouts/master.properties"
ADARO 92843: looking up 'header' using view engine
ENGINE-MUNGER 92843: trying locales ["DE/de"]
ENGINE-MUNGER 92843: lookup "header.js"
```

**Comment by nerdgore** [comment]
It seems the problem is related to adaro passing on it's onLoad options, rather than the request object that the initial call to lookup would receive from the view class itself.

**Comment by aredridel** [comment]
Whoops. I did re-arrange that for that release -- passing more information, but scoped -- so I may have missed a bit the tests did not cover.

**Comment by aredridel** [comment]
I think that this is actually a bug in adaro, and possibly already fixed by the changes in https://github.com/krakenjs/adaro/pull/92 -- can you try that and see if it helps?

**Comment by nerdgore** [comment]
Indeed, that solves the issue. Thanks for pointing that out.

**Comment by nerdgore** [comment]
This could be a dust or adaro issue but since engine-munger says it is loading the correct template while it is actually not I am posting this here:
If caching in adaro is turned on and I make a request that changes the language, then engine munger looks up the correct template but the original template is rendered.
So in my case I do the first request with `de-DE` and afterwards with `ru-RU`.

```
ENGINE-MUNGER 35273: trying locales ["RU/ru","DE/de"]
ENGINE-MUNGER 35273: lookup "home.js"
ENGINE-MUNGER 35273: stat "~/workspace/node-app/dist/node-app/build/app/views/RU/ru/home.js"
ENGINE-MUNGER 35273: found "~/workspace/node-app/dist/node-app/build/app/views/RU/ru/home.js"
ENGINE-MUNGER 35273: render "~/workspace/node-app/distnode-app/build/app/views/RU/ru/home.js"
GET /cph/?lang=ru 200 14.490 ms - -
```

**Comment by aredridel** [comment]
How are you changing languages? Without the full debug it's hard to tell, but I bet ru is still in the context.

**Comment by nerdgore** [comment]
It probably was dust related. I turned on caching in the adaro dust config and it stopped working.
It seems this was caused by the dust caching and that the compiled templates registered themselves with just their name: `home` vs `Ru/ru/home`.
I changed the registered name to include the locale and pass engine-munger a `formatPath` method that returns an empty string. Otherwise it would look for properties in `Ru/ru/Ru/ru` and so on. So my express file now looks like this:

``` javascript
    const DUST_CONFIG = {
            cache: !config.development,
            helpers: [
                "dustjs-helpers",
                "dust-makara-helpers",
                debug,
                resolve(app),
                inline,
                adv
            ]
        },
        I18N_FALLBACK = "de-DE",
        I18N_CONTENTPATH = "locales";

    app.set("view", munger({
        "js": {
            i18n: {
                contentPath: I18N_CONTENTPATH,
                fallback: I18N_FALLBACK,
                formatPath
            }
        },
        "properties": {
            root: [I18N_CONTENTPATH],
            i18n: {
                contentPath: I18N_CONTENTPATH,
                fallback: I18N_FALLBACK,
                // do not use the locale to generate the path for production
                // locale is already part of the template name
                formatPath: config.development ? formatPath : () => ""
            }
        }
    }));
```

**Comment by aredridel** [comment]
How are you compiling the templates? They should have their full names built in, not the short name.

That said, you can use the `dust` engine rather than js for production, because with caching, performance is comparable.

**Comment by nerdgore** [comment]
I was stripping the name after localising with localizr before compiling them with dust so that was a user error.
We have to use precompiling at the moment. We used to use makara but [with a large amount (11+) of partial includes it would hang](https://github.com/krakenjs/makara/issues/69) somewhere in the lookup/render pipeline when templates were not cached. If I cranked up the includes to 20 it would hang on the first request.
So far precompiling works without problems for us. I haven't had a chance to look deeper into the issue itself and I probably won't have time until end of September.

**Comment by aredridel** [comment]
Okay! I'm curious to see what you find -- any hangs like that are a bug, though i'm not sure where they'd lie.

There was a bug with 10+ outstanding lookups, but that is now fixed in 1.1.1

**Comment by aredridel** [comment]
(so I suspect you hit that bug, since partials happen in rapid sequence)

**Comment by nerdgore** [comment]
I'll try as soon as I can. Closing this issue for now since it is resolved for me. I'll update the other issues with my findings. Thank you for the help!
